import { index, layout, route, type RouteConfig } from "@react-router/dev/routes";

export default [
  layout("./route-modules/public-info-layout.tsx", { id: "public-info-layout" }, [
    route("faq", "./route-modules/faq.tsx", { id: "faq" }),
    route("termos", "./route-modules/termos.tsx", { id: "termos" }),
    route("privacidade", "./route-modules/privacidade.tsx", { id: "privacidade" }),
    route("lgpd", "./route-modules/lgpd.tsx", { id: "lgpd" }),
  ]),
  layout("./route-modules/main-layout.tsx", { id: "main-layout" }, [
    index("./route-modules/index-redirect.tsx", { id: "home-redirect" }),
    route("markets", "./route-modules/markets.tsx", { id: "markets" }),
    route("market/:id", "./route-modules/market-detail.tsx", { id: "market-detail" }),
    route("portfolio", "./route-modules/portfolio.tsx", { id: "portfolio" }),
    route("leaderboard", "./route-modules/leaderboard.tsx", { id: "leaderboard" }),
    route("settings", "./route-modules/settings.tsx", { id: "settings" }),
    route("auth", "./route-modules/auth.tsx", { id: "auth" }),
    route("fees", "./route-modules/fees.tsx", { id: "fees" }),
    route("referral", "./route-modules/referral.tsx", { id: "referral" }),
    route("profile", "./route-modules/profile.tsx", { id: "profile" }),
    route("profile/:userId", "./route-modules/profile.tsx", { id: "profile-user" }),
    route("suggestions", "./route-modules/suggestions.tsx", { id: "suggestions" }),
    route("suggestions/:id", "./route-modules/suggestion-detail.tsx", { id: "suggestion-detail" }),
    route("copy-traders", "./route-modules/copy-traders.tsx", { id: "copy-traders" }),
    route("trader/dashboard", "./route-modules/trader-dashboard.tsx", { id: "trader-dashboard" }),
  ]),
  route("admin/login", "./route-modules/admin-login.tsx", { id: "admin-login" }),
  route("admin", "./route-modules/admin-layout.tsx", { id: "admin-layout" }, [
    index("./route-modules/admin-dashboard.tsx", { id: "admin-dashboard" }),
    route("events", "./route-modules/admin-events.tsx", { id: "admin-events" }),
    route("events/new", "./route-modules/admin-event-form.tsx", { id: "admin-events-new" }),
    route("events/:id", "./route-modules/admin-event-detail.tsx", { id: "admin-events-detail" }),
    route("events/:id/edit", "./route-modules/admin-event-form.tsx", { id: "admin-events-edit" }),
    route("settlements", "./route-modules/admin-settlements.tsx", { id: "admin-settlements" }),
    route("audit", "./route-modules/admin-audit.tsx", { id: "admin-audit" }),
    route("financial", "./route-modules/admin-financial-overview.tsx", { id: "admin-financial" }),
    route("fees", "./route-modules/admin-fees.tsx", { id: "admin-fees" }),
    route("ledger", "./route-modules/admin-ledger.tsx", { id: "admin-ledger" }),
    route("revenue", "./route-modules/admin-revenue.tsx", { id: "admin-revenue" }),
    route("audit-logs", "./route-modules/admin-audit-logs.tsx", { id: "admin-audit-logs" }),
    route("users", "./route-modules/admin-users.tsx", { id: "admin-users" }),
    route("market-events", "./route-modules/admin-market-events.tsx", { id: "admin-market-events" }),
    route("referrals", "./route-modules/admin-referrals.tsx", { id: "admin-referrals" }),
    route("reports", "./route-modules/admin-reports.tsx", { id: "admin-reports" }),
    route("suggestions", "./route-modules/admin-suggestions.tsx", { id: "admin-suggestions" }),
    route("support", "./route-modules/admin-support.tsx", { id: "admin-support" }),
    route("copy-trade-settings", "./route-modules/admin-copy-trade-settings.tsx", { id: "admin-copy-trade-settings" }),
    route("copy-traders", "./route-modules/admin-copy-traders.tsx", { id: "admin-copy-traders" }),
    route("system", "./route-modules/admin-system.tsx", { id: "admin-system" }),
  ]),
  route("*", "./route-modules/not-found.tsx", { id: "not-found" }),
] satisfies RouteConfig;
