-- Adicionar novos tipos ao enum notification_type
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'DEPOSIT_CONFIRMED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'WITHDRAWAL_COMPLETED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'WITHDRAWAL_FAILED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'WITHDRAWAL_REQUESTED';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'PRICE_ALERT';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'COMMENT_MENTION';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'COMMENT_LIKE';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'COMMENT_REPLY';