export const SUPABASE_URL = "https://nfwxyftsdhgxfrnrvsdo.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5md3h5ZnRzZGhneGZybnJ2c2RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MDk0MTIsImV4cCI6MjA4MjM4NTQxMn0.k5RayzZDu6_5bYPznF0LD0kVaZbC7eOhXJOC8QwLe9Y";
